#!/usr/bin/env python3
"""Bakes every non-empty row of ramona_sheet.png into a looping GIF, plus an
index.html gallery to browse them - lets you see what's actually in the
sheet (used or not) without opening it frame-by-frame in an image editor.

Usage: python3 Scripts/make-sprite-previews.py
Output: cat_pack/ramona/previews/row{NN}.gif + index.html
"""
import os
from PIL import Image

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET_PATH = os.path.join(REPO_ROOT, "cat_pack/ramona/ramona_sheet.png")
OUT_DIR = os.path.join(REPO_ROOT, "cat_pack/ramona/previews")
CELL = 64
SCALE = 4
FRAME_DURATION_MS = 120


def row_frames(sheet, row):
    frames = []
    for col in range(14):
        frame = sheet.crop((col * CELL, row * CELL, col * CELL + CELL, row * CELL + CELL))
        if frame.getbbox() is None:
            break
        frames.append(frame)
    return frames


def main():
    sheet = Image.open(SHEET_PATH).convert("RGBA")
    rows = sheet.height // CELL
    os.makedirs(OUT_DIR, exist_ok=True)

    entries = []
    for row in range(rows):
        frames = row_frames(sheet, row)
        if not frames:
            continue
        scaled = [f.resize((CELL * SCALE, CELL * SCALE), Image.NEAREST) for f in frames]
        name = f"row{row:02d}.gif"
        scaled[0].save(
            os.path.join(OUT_DIR, name),
            save_all=True, append_images=scaled[1:], duration=FRAME_DURATION_MS,
            loop=0, disposal=2, transparency=0,
        )
        entries.append((row, len(frames), name))

    cards = "\n".join(
        f'  <div class="card"><h2>Row {row} - {count} frame{"s" if count != 1 else ""}</h2>'
        f'<img src="{name}" loading="lazy"></div>'
        for row, count, name in entries
    )
    html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Ramona sprite sheet preview</title>
<style>
  body {{ font-family: -apple-system, sans-serif; padding: 2rem; background: #1a1a1a; color: #eee; }}
  .grid {{ display: flex; flex-wrap: wrap; gap: 1.5rem; }}
  .card {{ text-align: center; width: 140px; }}
  .card img {{
    background:
      linear-gradient(45deg, #ffffff22 25%, transparent 25%, transparent 75%, #ffffff22 75%),
      linear-gradient(45deg, #ffffff22 25%, transparent 25%, transparent 75%, #ffffff22 75%);
    background-size: 16px 16px;
    background-position: 0 0, 8px 8px;
    image-rendering: pixelated;
    width: 140px;
    border-radius: 6px;
  }}
  h2 {{ font-size: 0.8rem; margin-bottom: 0.25rem; font-weight: 500; color: #aaa; }}
</style></head>
<body>
<h1>ramona_sheet.png - every row, animated</h1>
<p>Generated by Scripts/make-sprite-previews.py - {len(entries)} non-empty rows of {rows}.</p>
<div class="grid">
{cards}
</div>
</body></html>
"""
    with open(os.path.join(OUT_DIR, "index.html"), "w") as f:
        f.write(html)

    print(f"Wrote {len(entries)} GIFs + index.html to {OUT_DIR}")


if __name__ == "__main__":
    main()
